
  CREATE TABLE "TJOEUNIT"."BOOKCOMMENT" 
   (	"ISBN" NUMBER(*,0), 
	"NICK" VARCHAR2(2000 BYTE), 
	"IDX" NUMBER(*,0), 
	"SCORE" FLOAT(126), 
	"MEMO" CLOB, 
	"WDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MEMO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  

DROP SEQUENCE BOOKCOMMENT_idx_seq;
CREATE SEQUENCE BOOKCOMMENT_idx_seq;
DELETE FROM BOOKCOMMENT WHERE idx is null;
select * from bookcomment order by idx desc;
update bookcomment set category = 'it' where category is null;
delete bookcomment;


insert into bookcomment (isbn, NICK, IDX, SCORE, MEMO) values(102, 'ȫ�浿', (select NVL(MAX(IDX), 0) + 1 from bookcomment), 5, 'test');

select * from bookcomment where ISBN = 11 order by idx desc;








