CREATE TABLE "TJOEUNIT"."USERTABLE" 
   (	"USERNUM" NUMBER(*,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"NICK" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ID" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PW" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERTABLE_PK" PRIMARY KEY ("USERNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "NICK_UNQ" UNIQUE ("NICK", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

DROP SEQUENCE usertable_idx_seq;
CREATE SEQUENCE usertable_idx_seq;

select * from usertable

